### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by anandatheerthan** [kirankaranth1/facebook-comment-spammer#5] opened 2016-08-23 13:24 UTC
Hi,
I am getting "facepy.exceptions.OAuthError: [100] (#100) The 'limit' parameter should not exceed 250"
error upon executing the script.Any thoughts?

**Comment by nadarashwin** [comment] 2016-08-26 08:07
Hey dude,
You can update the  >>>  query = str(vid) + "/posts?fields=id&limit=200", so the limit has to be limited to max of 250.

**Comment by kirankaranth1** [comment] 2016-08-26 08:19
Sorry I saw this just now. Yes, the line query = str(vid) + "/posts?fields=id&limit= is what is causing this but previously whatever that number was, the number of posts returned was only 250 without returning any error, guess the API has changed a bit.

Yes changing that to limit=250 should solve the problem.

**Comment by kirankaranth1** [comment] 2016-08-26 08:22
[This commit](https://github.com/kirankaranth1/facebook-comment-spammer/commit/2babdb605803b4cdb1e6e19ca15ab6f6f5402757) should solve the problem. @anandatheerthan can you clone this now and check if the prolem remains?

**Comment by anandatheerthan** [comment] 2016-08-26 09:20
Thats worked, but I couldn't find the comment I gave in the posts.Below link is the output I got after execution.
`"www.facebook.com/1585647771718330/posts/1802022333414205"`

**Comment by kirankaranth1** [comment] 2016-08-26 09:36
@anandatheerthan This is different, similar to issue #4 . A token problem can be the reason for that and I haven't been able to reproduce it sadly. Closing this now.

**Closed by kirankaranth1** 2016-08-26 09:36 UTC

**Comment by anandatheerthan** [comment] 2016-08-26 10:10
thanks, i was generating page token instead of user token.. working fine now

**Comment by rubik1823** [comment] 2016-11-24 08:24
Hi, is there a way to do this with a friends profile?
When I input the Fb ID it's says that there are no spamable post
Regards!

**Comment by kirankaranth1** [comment] 2016-11-24 08:28
I'm assuming you're trying to spam a friend, whose ID is given as input. 

The thing I've observed with friend's profiles is that the first query in the script only returns posts that are "Public". So basically it will spam only on Public posts. To check just comment the lines where the like/comment actually happens and run the script on your own FB ID. It should return most of your posts.

**Comment by rubik1823** [comment] 2016-11-24 08:32
Thanks a lot... I tried but it doesn't work... 
However this is great!
Regards
